config/routes.rb
Rails.application.routes.draw do
  get "top", to: "abouts#top"
  root "abouts#top"
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update,] do
    resource :user_relationships, only: [:create, :destroy]
    resources :rooms, only: [:create]
  end
  resources :rooms, only: [:show, :index]  
  resources :user_relationships, only: [:index]

  mount ActionCable.server => "/cable"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :genre_relationships, dependent: :destroy
    has_many :genres, through: :genre_relationships, dependent: :destroy
end

app/models/genre_relationship.rb
class GenreRelationship < ApplicationRecord
    belongs_to :genre
    belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    belongs_to :room
    acts_as_paranoid

    validates :content, presence: true
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
    belongs_to :region
end

app/models/region.rb
class Region < ApplicationRecord
    has_many :prefectures, dependent: :destroy
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :genre_relationships, dependent: :destroy
  has_many :genres, through: :genre_relationships, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_many :active_relationships, class_name: "UserRelationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "UserRelationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  validates :name, presence: true
  validates :introduction, length: {maximum: 300}
  validates :name, length: {maximum: 10}
  validates :age, numericality: {only_integer: true}, inclusion: { in: 18..100 }, allow_blank: true
  acts_as_paranoid
  attachment :user_image

  # フォローされているかの確認
  def followed_by?(user)
    passive_relationships.where(following_id: user.id).present?
  end

  # バンドマン検索
  def self.search(instrument,sex,age_st,age_ed,region,level,introduction)
    if instrument.blank?
      search_instrument = User.all
    else
      search_instrument = User.where(instrument: "#{instrument}")
    end

    if sex.blank?
      search_sex = search_instrument.all
    else
      search_sex = search_instrument.where(sex: "#{sex}")
    end

    if region.blank?
      search_region = search_sex.all
    else
      search_region = search_sex.where(region: "#{region}")
    end

    if level.blank?
      search_level = search_region.all
    else
      search_level = search_region.where(level: "#{level}")
    end

    if introduction.blank?
      search_introduction = search_level.all
    else
      search_introduction = search_level.where("introduction LIKE ?","%#{introduction}%")
    end

    if age_st.blank? || age_ed.blank?
      search_age = search_introduction.all
    else
      search_age = search_introduction.where(age: age_st..age_ed)
    end

  end
  
end

app/models/user_relationship.rb
class UserRelationship < ApplicationRecord
    belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
    def top
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :baria_room, only: [:show]

  def create
    check_host = Room.where(host_id: current_user.id, member_id: params[:user_id]).exists?
    check_member = Room.where(host_id: params[:user_id], member_id: current_user.id).exists?
    if check_host || check_member == true
      if !check_host
        room = Room.where(host_id: params[:user_id], member_id: current_user.id).first
      else
        room = Room.where(host_id: current_user.id, member_id: params[:user_id]).first
      end
    else
      room = Room.new(host_id: current_user.id, member_id: params[:user_id])
      room.save
    end
    redirect_to room_path(room)
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages.with_deleted
    if @room.host_id == current_user.id
      @receive_user_id = @room.member_id
    else
      @receive_user_id = @room.host_id
    end
    @receive_user = User.with_deleted.where(id: @receive_user_id).first
  end

  def index
    user_messages = Message.with_deleted.where("(user_id = ?) OR (receiver_id = ?)", current_user, current_user)
    @user_messages = user_messages.order(created_at: :desc)
    @new_message = @user_messages.first
  end

  private

  def baria_room
    user_rooms = Room.where("(host_id = ?) OR (member_id = ?)", current_user,current_user)
    if user_rooms.where(id: params[:id]).empty?
      redirect_to user_path(current_user)
    end
  end

end

app/controllers/user_relationships_controller.rb
class UserRelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.new(follower_id: params[:user_id])
    follow.save
    @following = User.find(params[:user_id])
  end

  def destroy
    follow = current_user.active_relationships.where(follower_id: params[:user_id]).first
    follow.destroy
    @following = User.find(params[:user_id])
  end

  def index
    @followings = current_user.followings
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :baria_user, only: [:edit, :update]

  def index
    users_search = User.search(params[:instrument],params[:sex],params[:age_st],params[:age_ed],params[:region],params[:level],params[:introduction])
    @users_all = users_search.joins(:genres).where(genres: {genre_name: params[:genre_name]})
    if @users_all.count == 0
      @users_all = users_search
    end
    @per = 20
    @users = @users_all.page(params[:page]).per(@per)
  end

  def show
    @user = User.find(params[:id])
    @rooms = Room.where("(host_id = ?) OR (member_id = ?)", current_user,current_user).order(created_at: :desc)
    user_messages = Message.with_deleted.where("(user_id = ?) OR (receiver_id = ?)", current_user, current_user)
    @user_messages = user_messages.order(created_at: :desc)
    @new_message = @user_messages.first
    @count_all = 0
    @rooms.each do |room|
      if message = room.messages.with_deleted.order(created_at: :desc).first
        if message.created_at.to_date == Date.today
          @count_all += 1
        end
      end
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報が更新されました"
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :sex, :age, :instrument, :level, :region, :introduction, :chat_flag, :email, :user_image, genre_ids: [])
  end

  def baria_user
    user = User.find(params[:id])
    if user != current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_relationships_helper.rb
module UserRelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/abouts/top.html.erb
<div id="top_back_image">
  <div class="container">
    <div class="row">
      <div class="col-xs-offset-2 col-xs-8">
        <div class="notice"><%= notice %></div>
        <div id="top_back">
          <div class="top_title">Welcome to SESSION</div>
          <div class="top_body">
            <div>SESSIONはバンドメンバーを募集するためのアプリです。</div>
            <div>あなたの条件にあったバンドマンを検索して、バンドに勧誘しましょう!</div>
          </div>
          <%= link_to users_path do %>
            <div class="first_action">
              <div>バンドマンを</div>
              <div>検索する</div>
            </div>
          <% end %>
          <%= link_to new_user_registration_path do %>
            <div class="first_action">
              <div>SESSIONに</div>
              <div>登録する</div>
            </div>
          <% end %>
          <div id="about_move" class="first_action">
            <div>SESSIONを</div>
            <div>もっと知る</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-offset-2 col-xs-8">
      <div class="top_back_white">
        <div class="about">
          <div class="about_title">SESSIONとは？</div>
          <div class="col-xs-12">
            <div class="about_box_first">
              <div class="about_box_back">
                <div class="col-xs-1"></div>
                <div class="col-xs-10">
                  <div class="about_head">
                    <div>複数の条件から</div>
                    <div>バンドマンを検索できる！</div>
                  </div>
                  <div class="about_body">
                    <div>楽器や地域等の情報の他、プレイレベルからも</div>
                    <div>バンドマンを検索することができます。</div>
                  </div>
                </div>
              </div>
            </div>
            <div class="about_box_second">
              <div class="about_box_back">
                <div class="col-xs-1"></div>
                <div class="col-xs-10">
                  <div class="about_head">
                    <div>チャットで</div>
                    <div>メンバーを勧誘できる！</div>
                  </div>
                  <div class="about_body">
                    <div>会員登録をすることで、</div>
                    <div>検索したバンドマンとチャットをすることができます。</div>
                  </div>
                </div>
              </div>
            </div>
            <div class="about_box_third">
              <div class="about_box_back">
                <div class="col-xs-1"></div>
                <div class="col-xs-10">
                  <div class="about_head">
                    <div>自分の要望にあった</div>
                    <div>メンバーを募集できる！</div>
                  </div>
                  <div class="about_body">
                    <div>会員登録をすることで、</div>
                    <div>プロフィールを基にバンドメンバーを募集できます。</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div id="about_botton">SESSIONを利用する</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_follow.html.erb
<% if user_signed_in? %>
  <% if current_user != following %>
    <% if following.followed_by?(current_user) %>
      <%= link_to user_user_relationships_path(following), method: :delete, remote: true do %>
        <span class="glyphicon glyphicon-heart follow_icon" aria-hidden="true"></span>
      <% end %>
    <% else %>
      <%= link_to user_user_relationships_path(following), method: :post, remote: true do %>
        <span class="glyphicon glyphicon-heart-empty follow_icon" aria-hidden="true"></span>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_search.html.erb
<div id="page_count_move">
  <span class="page_count">
    <% if @users.count == 0 %>0 〜
    <% else %>
      <%= @users.current_page * @per - @per + 1 %>〜
    <% end %>
    <%= @users.current_page * @per - @per + @users.count %>件目を表示 / 全
    <%= @users_all.count %>件
  </span>
</div>

<table class="table table-hover">
  <% @users.each do |user|%>
    <tr>
      <td class="col-xs-1">
        <%= attachment_image_tag(user, :user_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50") %>
      </td>
      <td>
        <div>
          <%= link_to user_path(user) do %>
            <span class="name"><%= user.name.truncate(7) %></span>
            <span class="info">
              <% if user.instrument.blank? %>
                未登録
              <% else %>
                <%= user.instrument %>
              <% end %>
            </span>
            <span class="info">
              <% if user.region.blank? %>
                未登録
              <% else %>
                <%= user.region %>
              <% end %>
            </span>
            <span class="info">
              <% if user.level.blank? %>
                未登録
              <% else %>
                Level.<%= user.level %>
              <% end %>
            </span>
            <% limit = 3 %>
            <% user.genres. each do |genre| %>
              <% break if limit == 0 %>
              <% limit -= 1 %>
              <span class="genre_icon"><%= genre.genre_name %></span>
            <% end %>
            <% limit.times do %>
              <span class="genre_icon">未登録</span>
            <% end %>
          <% end %>

          <% following = user %>
          <span id="follow_<%= following.id %>">
            <%= render partial:"layouts/follow", locals: {following: following} %>
          </span>
        </div>

        <%= link_to user_path(user) do %>
          <span class="intro">
            <% if user.introduction == nil %>
              <%= user.introduction %>
            <% else %>
              <%= user.introduction.truncate(88) %>
            <% end %>
          </span>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<div class="page_count">
  <%if @users.count >= 9 %>
    <% if @users.count == 0 %>0 〜
    <% else %>
      <%= @users.current_page * @per - @per + 1 %>〜
    <% end %>
    <%= @users.current_page * @per - @per + @users.count %>件目を表示 / 全
    <%= @users_all.count %>件
  <% end %>
</div>
<%= paginate @users %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Session</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-inverse">
        <div class="container">
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
              <div class="navbar-header">
                <%= link_to "SESSION", root_path, class:"session"%>
              </div>
              <% if user_signed_in? %>
                <div>
                  <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "メンバー検索", users_path %></li>
                    <li><%= link_to "マイページ", user_path(current_user.id) %></li>
                    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                  </ul>
                </div>
              <% else %>
                <ul class="nav navbar-nav navbar-right">
                  <li><%= link_to "メンバー検索", users_path %></li>
                  <li><%= link_to "新規登録", new_user_registration_path %></li>
                  <li><%= link_to "ログイン", new_user_session_path %></li>
                </ul>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
      <div class="current_user_back">
        <div class="current_user">
          <div class="container">
            <div class="row">
              <div class="col-xs-8 col-xs-offset-2">
                <% if user_signed_in? %>
                  <div><%= current_user.name %>さんがログイン中</div>
                  <input type="hidden" id="current_user_id" value="<%= current_user.id %>">
                  <% if chat_flag = current_user.chat_flag %>
                    <input type="hidden" id="chat_flag" value="<%= current_user.chat_flag %>">
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <div id="page_top"><span class="glyphicon glyphicon-circle-arrow-up" aria-hidden="true"></span></div>
    <%= yield %>
  </body>
</html>

app/views/user_relationships/create.js.erb
$("#follow_<%= @following.id %>").html("<%= j(render partial: "layouts/follow", locals: {following: @following}) %>");

app/views/user_relationships/destroy.js.erb
$("#follow_<%= @following.id %>").html("<%= j(render partial: "layouts/follow", locals: {following: @following}) %>");

app/views/users/index.html.erb
<div id="back_image">
  <div id="back_image_effect">
    <div class="container">
      <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
          <div class="search_window_back">
            <div class="search_window">
              <%= form_with(url: users_path, method: :get) do |f| %>
                <div class="title">楽器</div>
                <%= f.select :instrument, ["","ギター","ベース","ドラム","ボーカル","キーボード","作詞担当","作曲担当","その他"], {}, {autofocus:"ture", class:"search_form"} %>
                <div class="title">ジャンル</div>
                <%= f.collection_select :genre_name, Genre.all, :genre_name, :genre_name, include_blank: true %>
                <div class="title">性別</div>
                <%= f.select :sex, ["","男性","女性"], {}, {class:"search_form"}  %>
                <div class="title">年齢</div>
                <%= f.number_field :age_st, class:"search_age" %>
                <span class="title">〜</span>
                <%= f.number_field :age_ed, class:"search_age" %>
                <div class="title">活動地域</div>
                <%= f.grouped_collection_select(:region, Region.all, :prefectures, :region_name, :prefecture_name, :prefecture_name, include_blank: true) %>
                <div class="title">自己評価点(Level)</div>
                <%= f.select :level, [["",""],["1 (初心者)","1"],["2 (簡単な曲なら弾ける)","2"],["3 (簡単な曲なら耳コピができる)","3"],["4 (簡単なセッションができる)","4"],["5 (セッションができる)","5"]], {}, {class:"search_form"} %>
                <div class="title">キーワード</div>
                <p><%= f.text_field :introduction, class:"text" %></p>
                <%= f.submit "検索", class:"submit btn btn-primary", id:"search_input" %>
              <% end %>
            </div>
          </div>

          <div class="search_result_back">
            <div class="index_white_back">
              <span id="search">
                <%= render partial:"layouts/search" %>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.js.erb
$("#search").html("<%= j(render partial: "layouts/search") %>");

$("#page_count_move").animate({
  "paddingTop": "10px"
}).animate({
  "paddingTop": "0px"
});

app/views/users/show.html.erb
<div class="back_gray">
  <div class="container">
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="back_white">
          <% if @user == current_user %>
            <div class="notice"><%= notice %></div>
            <div class="float_window">
              <span class="message_titile">最近の投稿</span>
              <span class="small_text">(本日は<%= @count_all %>件の投稿があります)</span>
              <table class="table table-hover">
                <% if @new_message.nil? %>
                  <tr>
                    <td class="small_text">
                      <%= link_to users_path do %>
                        <span>バンドマンを検索して、チャットをしてみましょう！</span>
                      <% end %>
                    </td>
                  </tr>
                <% else%>
                  <tr>
                    <% room = @new_message.room %>
                    <% if room.host_id == current_user.id %>
                      <% user = User.with_deleted.where(id: room.member_id).first %>
                      <td class="col-xs-1">
                        <%= link_to room_path(room) do %>
                          <% if user.deleted_at == nil %>
                            <%= attachment_image_tag(user, :user_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50") %>
                          <% else %>
                            <%= image_tag"no_image.jpg", id:"message_image" %>
                          <% end %>
                        <% end %>
                      </td>
                      <td>
                        <%= link_to room_path(room) do %>
                          <span class="room_name"><%= user.name %></span>
                        <% end %>
                      </td>
                    <% else %>
                      <% user = User.with_deleted.where(id: room.host_id).first %>
                      <td class="col-xs-1">
                        <%= link_to room_path(room) do %>
                          <% if user.deleted_at == nil %>
                            <%= attachment_image_tag(user, :user_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50") %>
                          <% else %>
                            <%= image_tag"no_image.jpg", id:"message_image" %>
                          <% end %>
                        <% end %>
                      </td>
                      <td>
                        <%= link_to room_path(room) do %>
                          <span class="room_name"><%= user.name %></span>
                        <% end %>
                      </td>
                    <% end %>
                    <td>
                      <%= link_to room_path(room) do %>
                        <div class="time"><%= @new_message.created_at.strftime('%m/%d %H:%M') %></div>
                        <div class="new_message"><%= @new_message.content.truncate(20) %></div>
                      <% end %>
                    </td>
                  </tr>
                  <% room_id = @new_message.room_id %>
                  <% old_message = @user_messages.where.not(room_id: room_id) %>
                  <% message = old_message.order(created_at: :desc).first %>

                  <% limit = 0 %>
                  <% while old_message.count > 0 %>
                    <% break if limit == 3 %>
                    <% limit += 1 %>
                    <tr>
                      <% room = message.room %>
                      <% if room.host_id == current_user.id %>
                        <% user = User.with_deleted.where(id: room.member_id).first %>
                        <td class="col-xs-1">
                          <%= link_to room_path(room) do %>
                            <% if user.deleted_at == nil %>
                              <%= attachment_image_tag(user, :user_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50") %>
                            <% else %>
                              <%= image_tag"no_image.jpg", id:"message_image" %>
                            <% end %>
                          <% end %>
                        </td>
                        <td>
                          <%= link_to room_path(room) do %>
                            <span class="room_name"><%= user.name %></span>
                          <% end %>
                        </td>
                      <% else %>
                        <% user = User.with_deleted.where(id: room.host_id).first %>
                        <td class="col-xs-1">
                          <%= link_to room_path(room) do %>
                            <% if user.deleted_at == nil %>
                              <%= attachment_image_tag(user, :user_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50") %>
                            <% else %>
                              <%= image_tag"no_image.jpg", id:"message_image" %>
                            <% end %>
                          <% end %>
                        </td>
                        <td>
                          <%= link_to room_path(room) do %>
                            <span class="room_name"><%= user.name %></span>
                          <% end %>
                        </td>
                      <% end %>
                      <td>
                        <%= link_to room_path(room) do %>
                          <div class="time"><%= message.created_at.strftime('%m/%d %H:%M') %></div>
                          <div class="new_message"><%= message.content.truncate(20) %></div>
                        <% end %>
                      </td>
                    </tr>
                    <% room_id = message.room_id %>
                    <% old_message = old_message.where.not(room_id: room_id) %>
                    <% message = old_message.order(created_at: :desc).first %>
                  <% end %>
                <% end %>
              </table>
              <%= link_to rooms_path, class:"btn btn-primary" do %>
                <span>チャットルームを全件表示する</span>
              <% end %>
            </div>

            <div class="float_window">
              <span class="message_titile">お気に入り</span>
              <table class="table table-hover">
                <% if current_user.followings.blank? %>
                  <tr>
                    <td class="small_text">
                      <%= link_to users_path do %>
                        <span class="glyphicon glyphicon-heart-empty follow_icon" aria-hidden="true"></span>
                        <span>をクリックして、気になるバンドマンをお気に入りに登録してみましょう！</span>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
                <% following_count = 0 %>
                <% current_user.followings.each do |following| %>
                  <% break if following_count == 3 %>
                  <% following_count += 1 %>
                  <tr>
                    <td class="col-xs-1">
                      <%= attachment_image_tag(following, :user_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50") %>
                    </td>
                    <td>
                      <div>
                        <%= link_to user_path(following) do %>
                          <span class="name"><%= following.name.truncate(7) %></span>
                          <span class="info">
                            <% if following.instrument.blank? %>
                              未登録
                            <% else %>
                              <%= following.instrument %>
                            <% end %>
                          </span>
                          <span class="info">
                            <% if following.level.blank? %>
                              未登録
                            <% else %>
                              Level.<%= following.level %>
                            <% end %>
                          </span>

                          <% limit = 2 %>
                            <% following.genres. each do |genre| %>
                              <% break if limit == 0 %>
                              <% limit -= 1 %>
                              <span class="genre_icon"><%= genre.genre_name %></span>
                            <% end %>
                            <% limit.times do %>
                              <span class="genre_icon">未登録</span>
                            <% end %>
                          <% end %>
                        
                        <span id="follow_<%= following.id %>">
                          <%= render partial:"layouts/follow", locals: {following: following} %>
                        </span>
                      </div>
                      <%= link_to user_path(following) do %>
                        <span class="intro">
                          <% if !following.introduction.blank? %>
                            <%= following.introduction.truncate(88) %>
                          <% end %>
                        </span>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </table>
              <%= link_to user_relationships_path, class:"btn btn-primary" do %>
                <span>お気に入りを全件表示する</span>
              <% end %>
            </div>
          <% end %>

          <div class="float_window">
            <span class="message_titile">プロフィール</span>
            <table class="table">
              <tr>
                <th class="title">画像</th>
                <td>
                  <%= attachment_image_tag(@user, :user_image, :fill, 200, 200, fallback: "no_image.jpg", size: "200x200") %>
                </td>
              </tr>
              <tr>
                <th class="title">ニックネーム</th>
                <td class="field">
                  <%= @user.name %>
                </td>
              </tr>

              <tr>
                <th class="title">性別</th>
                <td class="field">
                  <%= @user.sex %>
                </td>
              </tr>

              <tr>
                <th class="title">年齢</th>
                <td class="field">
                  <%= @user.age %>
                </td>
              </tr>

              <tr>
                <th class="title">担当楽器</th>
                <td class="field">
                  <%= @user.instrument %>
                </td>
              </tr>

              <tr>
                <th class="title">自己評価点</th>
                <td class="field">
                  <%= @user.level %>
                </td>
              </tr>

              <tr>
                <th class="title">活動地域</th>
                <td class="field">
                  <%= @user.region %>
                </td>
              </tr>

              <tr>
                <th>ジャンル</th>
                <td>
                  <% @user.genres. each do |genre| %>
                    <span class="genre_icon"><%= genre.genre_name  %></span>
                  <% end %>
                </td>
              </tr>
              <tr>
                <th class="title">自己紹介</th>
                <td>
                  <%= @user.introduction %>
                </td>
              </tr>
            </table>
            <% if @user == current_user %>
              <% if @user.chat_flag == false %>
                <div class="btn btn-default btn-md">チャット不可</div>
              <% elsif @user.chat_flag == true %>
                <div class="btn btn-primary btn-md">チャット可能</div>
              <% end %>
              <%= link_to "編集する", edit_user_path, class:"btn btn-primary btn-md" %>
            <% else %>
              <% if @user.chat_flag == false %>
                <div class="btn btn-default btn-md">チャット不可</div>
              <% else %>
                <% if user_signed_in? %>
                  <%= link_to "チャットしてみる", user_rooms_path(@user), method: :post, class:"btn btn-primary btn-md" %>
                <% else %>
                  <%= link_to "チャットしてみる", new_user_registration_path, class:"btn btn-primary btn-md", data: {confirm: "チャットをするには会員登録が必要です"} %>
                <% end %>
              <% end %>

              <% following = @user %>
              <span id="follow_<%= following.id %>">
                <%= render partial:"layouts/follow", locals: {following: following} %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>